include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - sort_pub_dependencies
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_relative_lib_imports
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_this

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
